import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/layout/Header"
import Fotter from '@/components/layout/Fotter'
import Providers from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <Providers>
      <Header />
<main className='px-6 '>
{children}

</main>

<Fotter />
</Providers>
        
        
        </body>
    </html>
  )
}
